version: '3.8'

services:
  redis:
    image: redis:8.0-alpine
    container_name: redis-cache
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "your_redis_password"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  user-management-db:
    image: postgres:15-alpine
    container_name: dailyspendingand-expenditure-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: B3YOND
      POSTGRES_DB: Backend
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:
    name: user-management-db-data
    driver: local

  redis-data:
    name: redis-cache-data
    driver: local

networks:
  app-network:
    driver: bridge
