[
  {
    "name": "Esthy Ambetsa",
    "email": "esthyambetsa@gmail.com",
    "password": "Esthy123",
    "role": "ADMIN"
  },
  {
    "name": "Larry",
    "email": "larry@gmail.com",
    "password": "Larry123",
    "role": "ADMIN"
  },
  {
    "name": "New Admin",
    "email": "newadmin@gmail.com",
    "password": "Admin123",
    "role": "ADMIN"
  },
  {
    "name": "Thaddeaus",
    "email": "thaddeaus@gmail.com",
    "password": "Thaddeaus123",
    "role": "USER"
  },
  {
    "name": "Paul Larry",
    "email": "paullarry@gmail.com",
    "password": "PaulLarry123",
    "role": "USER"
  },
  {
    "name": "Diana Achieng",
    "email": "diana@gmail.com",
    "password": "Diana123",
    "role": "USER"
  },
  {
    "name": "Grace Wanjiru",
    "email": "grace@gmail.com",
    "password": "Grace123",
    "role": "USER"
  },
  {
    "name": "Luke Smith",
    "email": "lukesmith@gmail.com",
    "password": "Luke123",
    "role": "USER"
  }
]


//CATEGORIES
[
  {
    "name": "Esthy Ambetsa",
    "email": "esthyambetsa@gmail.com",
    "password": "Esthy123",
    "role": "ADMIN",
    "categories": [
      { "name": "Groceries" },
      { "name": "Electronics" },
      { "name": "Clothing" }
    ]
  },
  {
    "name": "Larry",
    "email": "larry@gmail.com",
    "password": "Larry123",
    "role": "ADMIN",
    "categories": [
      { "name": "Books" },
      { "name": "Groceries" },
      { "name": "Sports" }
    ]
  },
  {
    "name": "New Admin",
    "email": "newadmin@gmail.com",
    "password": "Admin123",
    "role": "ADMIN",
    "categories": [
      { "name": "Clothing" },
      { "name": "Health" },
      { "name": "Groceries" }
    ]
  },
  {
    "name": "Thaddeaus",
    "email": "thaddeaus@gmail.com",
    "password": "Thaddeaus123",
    "role": "USER",
    "categories": [
      { "name": "Groceries" },
      { "name": "Furniture" },
      { "name": "Toys" }
    ]
  },
  {
    "name": "Paul Larry",
    "email": "paullarry@gmail.com",
    "password": "PaulLarry123",
    "role": "USER",
    "categories": [
      { "name": "Electronics" },
      { "name": "Clothing" },
      { "name": "Sports" }
    ]
  },
  {
    "name": "Diana Achieng",
    "email": "diana@gmail.com",
    "password": "Diana123",
    "role": "USER",
    "categories": [
      { "name": "Books" },
      { "name": "Groceries" },
      { "name": "Clothing" }
    ]
  },
  {
    "name": "Grace Wanjiru",
    "email": "grace@gmail.com",
    "password": "Grace123",
    "role": "USER",
    "categories": [
      { "name": "Health" },
      { "name": "Groceries" },
      { "name": "Electronics" }
    ]
  },
  {
    "name": "Luke Smith",
    "email": "lukesmith@gmail.com",
    "password": "Luke123",
    "role": "USER",
    "categories": [
      { "name": "Sports" },
      { "name": "Furniture" },
      { "name": "Books" }
    ]
  }
]
