### Seed the database with users
POST http://localhost:8000/seed
Content-Type: application/json

###



### Get all users
GET http://localhost:8000/users
Accept: application/json

###

### Get user with id 1
GET http://localhost:8000/users/1
Accept: application/json

###



### Delete user with id 1
DELETE http://localhost:8000/users/1

### Sign in to get access token
POST http://localhost:8000/auth/signin
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "password123"
}

### Use the access token (replace YOUR_ACCESS_TOKEN with the token from signin response)
GET http://localhost:8000/users
Authorization: Bearer YOUR_ACCESS_TOKEN

### Check if user exists
GET http://localhost:8000/users
Accept: application/json
