### Seed the database with users
POST http://localhost:8000/seed
Content-Type: application/json

###

### Get all users
GET http://localhost:8000/users
Accept: application/json

###

### Get user with id 1
GET http://localhost:8000/users/1
Accept: application/json

###

### Create a new user
POST http://localhost:8000/users
Content-Type: application/json

{
  "username": "John Doe",
  "email": "john.doe@example.com",
  "password": "secret123",
  "role": "USER"
}

###

### Delete user with id 1
DELETE http://localhost:8000/users/1
