### 1. Create test user first
POST http://localhost:8000/users
Content-Type: application/json

{
    "name": "timothy ",
    "email": "nandwakhalay@gmail.com",
    "password": "password123",
    "role": "ADMIN"
}

### 2. Sign in to get tokens
POST http://localhost:8000/auth/signin
Content-Type: application/json

{
   "email": "nandwakhalay@gmail.com",
    "password": "password123"
}


### 4. Test protected route with token
GET http://localhost:8000/users
Authorization: Bearer {{"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcwLCJlbWFpbCI6Im5hbmR3YWtoYWxheUBnbWFpbC5jb20iLCJpYXQiOjE3NDkzMjU1NzgsImV4cCI6MTc0OTMyNTg3OH0.wWhanNZe100A1mLr4x0gu1p_w_9Rzg0E0sOM-6hoqiQ"}}

### 5. Sign out (make sure to use actual user ID)
POST http://localhost:8000/auth/signout/70
Authorization: Bearer {{"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcwLCJlbWFpbCI6Im5hbmR3YWtoYWxheUBnbWFpbC5jb20iLCJpYXQiOjE3NDkzMjU1NzgsImV4cCI6MTc0OTMyNTg3OH0.wWhanNZe100A1mLr4x0gu1p_w_9Rzg0E0sOM-6hoqiQ"}}

### 6. Refresh token
POST http://localhost:8000/auth/refresh
Authorization: Bearer {{"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcwLCJlbWFpbCI6Im5hbmR3YWtoYWxheUBnbWFpbC5jb20iLCJpYXQiOjE3NDkzMjU1NzgsImV4cCI6MTc0OTMyNTg3OH0.wWhanNZe100A1mLr4x0gu1p_w_9Rzg0E0sOM-6hoqiQ"}}


